---

- name: removes subscription nag box
  include: remove-nag.yml
  when: remove_nag

- name: remove enterprise repo
  include: remove-enterprise-repo.yml
  when: remove_enterprise_repo

- name: add no subcription repo
  include: add-no-subcription-repo.yml
  when: add_no_subscription_repo
