---

- name: Get pveversion for backup file
  shell: "pveversion | awk -F / '{print $2}'"
  register: pveversion

- name: backup up original file
  copy:
    remote_src: True
    src: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    dest: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak-{{ pveversion.stdout }}"
    force: no

- name: modify line which performs license check
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: "data.status \\!== \\'Active\\'"
    replace: "false"
  notify: restart pveproxy
